<template>
  <div class="bg">
    <div class="ceshi">
    <el-tree
      :data="treeData"
      show-checkbox
      default-expand-all
      node-key="menucode"
      ref="tree"
      highlight-current
      :props="defaultProps"
      :default-checked-keys="checkedKeys"
      id="tree"
    ></el-tree>
    <div class="btn">
      <el-button  type="text" size="medium" @click="getCheckedKeys">修改权限</el-button>
    </div>
  </div>
  </div>
  
</template>
<script>
export default {
  props: {
    msg: String,
  },
  data() {
    return {
      res: {
        result: [
          {
            leafflag: "0",
            loginid: "999",
            loginpwd: "999",
            menucode: "110000",
            menuname: "用户管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "0",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "110100",
            menuname: "用户查询",
            menuremark: "",
            menuurl: "/home/userquery",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110101",
            menuname: "基本信息",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110102",
            menuname: "档案信息",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110103",
            menuname: "计划信息",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "110200",
            menuname: "用户统计",
            menuremark: "",
            menuurl: "/home/userstatistics",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110201",
            menuname: "按年龄",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110202",
            menuname: "按渠道",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110203",
            menuname: "按体征",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110204",
            menuname: "按性别",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110205",
            menuname: "按注册时间",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "110300",
            menuname: "健康档案查询",
            menuremark: "",
            menuurl: "/home/healthfile",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "110400",
            menuname: "健康计划管理",
            menuremark: "",
            menuurl: "/home/healthplan",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110401",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110402",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110403",
            menuname: "启用/停止",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110404",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "110500",
            menuname: "健康咨询管理",
            menuremark: "",
            menuurl: "/home/",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110501",
            menuname: "视频",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110500",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110502",
            menuname: "图文",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110500",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "110503",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "110500",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "0",
            loginid: "999",
            loginpwd: "999",
            menucode: "120000",
            menuname: "渠道管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "0",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "120100",
            menuname: "渠道信息维护",
            menuremark: "",
            menuurl: "/home/channelmanager",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120101",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120102",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120103",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120104",
            menuname: "启用/停止",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120105",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "120200",
            menuname: "渠道用户统计",
            menuremark: "",
            menuurl: "/home/channeluser",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "120300",
            menuname: "渠道佣金结算",
            menuremark: "",
            menuurl: "/home/channelcommission",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120301",
            menuname: "计算",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120302",
            menuname: "结算",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120303",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "120400",
            menuname: "渠道订单管理",
            menuremark: "",
            menuurl: "/home/channelorder",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120401",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120402",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120403",
            menuname: "取消",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120404",
            menuname: "结算",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120405",
            menuname: "发货",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "120406",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "120400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "0",
            loginid: "999",
            loginpwd: "999",
            menucode: "130000",
            menuname: "服务站管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "0",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "130100",
            menuname: "服务站信息维护",
            menuremark: "",
            menuurl: "/home/serviceinformation",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130101",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130102",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130103",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130104",
            menuname: "启用/停用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130105",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "130200",
            menuname: "服务站用户统计",
            menuremark: "",
            menuurl: "/home/serviceuser",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "130300",
            menuname: "服务站佣金结算",
            menuremark: "",
            menuurl: "/home/servicefees",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130301",
            menuname: "计算",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130302",
            menuname: "结算",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130303",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "130400",
            menuname: "服务站订单管理",
            menuremark: "",
            menuurl: "/home/serviceorder",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130401",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130402",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130403",
            menuname: "取消",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130404",
            menuname: "结算",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130405",
            menuname: "发货",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "130406",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "130400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "0",
            loginid: "999",
            loginpwd: "999",
            menucode: "140000",
            menuname: "健康科普管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "0",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "140100",
            menuname: "科普信息维护",
            menuremark: "",
            menuurl: "/home/maintain",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "140101",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "140102",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "140103",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "140104",
            menuname: "启用/停用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "140105",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "140200",
            menuname: "科普信息分析",
            menuremark: "",
            menuurl: "/home/analyze",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "140000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "0",
            loginid: "999",
            loginpwd: "999",
            menucode: "180000",
            menuname: "操作员管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "0",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "180100",
            menuname: "角色管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180101",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180102",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180103",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180104",
            menuname: "权限",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180105",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "180200",
            menuname: "平台操作员管理",
            menuremark: "",
            menuurl: "/home/platform",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180201",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180202",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180203",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180204",
            menuname: "角色",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180205",
            menuname: "清密",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180206",
            menuname: "启用/停用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180207",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "180300",
            menuname: "渠道操作员管理",
            menuremark: "",
            menuurl: "/home/channel",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180301",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180302",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180303",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180304",
            menuname: "启用/停用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180305",
            menuname: "清密",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180306",
            menuname: "角色",
            menuremark: "",
            menuurl: "/home/role",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180307",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180300",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "180400",
            menuname: "服务站操作员管理",
            menuremark: "",
            menuurl: "/home/service",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180401",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180402",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180403",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180404",
            menuname: "启用/停用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180405",
            menuname: "清密",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180406",
            menuname: "角色",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "180407",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "180400",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "0",
            loginid: "999",
            loginpwd: "999",
            menucode: "190000",
            menuname: "系统参数管理",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "0",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "190100",
            menuname: "菜单管理",
            menuremark: "",
            menuurl: "/home/menus",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190101",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190102",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190103",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190104",
            menuname: "停用/启用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190105",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190100",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "190200",
            menuname: "数据字典维护",
            menuremark: "",
            menuurl: "/home/datadictionary",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190201",
            menuname: "增加",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190202",
            menuname: "修改",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190203",
            menuname: "删除",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190204",
            menuname: "启用/停用",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "2",
            loginid: "999",
            loginpwd: "999",
            menucode: "190205",
            menuname: "查询",
            menuremark: "",
            menuurl: "",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190200",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
          {
            leafflag: "1",
            loginid: "999",
            loginpwd: "999",
            menucode: "190300",
            menuname: "控制参数维护",
            menuremark: "",
            menuurl: "/home/control",
            menuvalidflag: "1",
            mobilenbr: "13958185810",
            opercode: "999999",
            opername: "系统管理员1",
            parmenucode: "190000",
            parrolecode: "0",
            remark: "",
            rolecode: "999999",
            rolename: "系统管理员角色",
            roleremark: "",
            rolevalidflag: "1",
            validflag: "1",
          },
        ],

        opercode: "999999",
        opername: "系统管理员1",
        logintoken: "b3TVeWOuS6P/wqNektQXvr65nbQ=",
        message: "亲,登录成功!",
      },
      // 节点遍历数据
      treeData: [],
      // 节点控制参数
      defaultProps: {
        children: "child",
        label: "menuname",
      },
      // 节点默认选中
      checkedKeys:[]
      
    };
  },
  methods: {
    getCheckedKeys() {
      console.log(this.$refs.tree.getCheckedKeys());
    },

    find() {
      var newArr1 = [];
      var newArr2 = [];
      var newArr3 = [];
      let arr = this.res.result;

      for (let i = 0; i < arr.length; i++) {
        if (arr[i].leafflag == "0") {
          newArr1.push(arr[i]);
        }
        if (arr[i].leafflag == "1") {
          newArr2.push(arr[i]);
        }
        if (arr[i].leafflag == "2") {
          newArr3.push(arr[i]);
        }
        this.checkedKeys.push(arr[i].menucode)
      }

      for (var a = 0; a < newArr1.length; a++) {
        newArr1[a].child = [];
        for (var b = 0; b < newArr2.length; b++) {
          if (newArr1[a].menucode == newArr2[b].parmenucode) {
            newArr1[a].child.push(newArr2[b]);
          }
          newArr2[b].child = [];
          for (var c = 0; c < newArr3.length; c++) {
            if (newArr2[b].menucode == newArr3[c].parmenucode) {
              newArr2[b].child.push(newArr3[c]);
            }
          }
        }
      }
      this.treeData = newArr1;
    },
  },
  mounted() {
    this.find();
    console.log(this.checkedKeys)
    console.log(this.res);
    console.log(this.treeData);
  },
};
</script>
<style  lang='stylus'>
.bg
  width 100vw
  height 100vh
  position fixed
  background rgba(0,0,0,0.6)
  display flex
  justify-content center
  .ceshi
    clear:both;
    width 75%
    margin 40px auto 0px

    #tree
      width 100%
      display flex
      justify-content space-around
      background #f4f4f4
      padding 20px 0 0px

      &>div 
        background #f0f0f0
        padding 10px 30px 10px 10px
        border 1px solid #ccc
    .btn 
      text-align right
      padding-right 30px
      padding-top 10px
      background #f4f4f4
</style>